[build]
default-target = "aarch64-unknown-linux-gnu"    # use this target if none is explicitly provided

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libasound2-dev:$CROSS_DEB_ARCH"
]